name = "shine_tree"
version = "0.0.1"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
description = "A `FingerTree` implementation for general purpose functional programming in Gleam!"
licences = ["MIT"]
repository = { type = "github", user = "shine-coders", repo = "shine_tree" }
# links = [{ title = "Website", href = "" }]

target = "erlang"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
pprint = ">= 1.0.3 and < 2.0.0"
simplifile = ">= 2.1.0 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
glychee = ">= 1.1.2 and < 2.0.0"

[documentation]
pages = [
  { title = "Benchmarks", path = "benchmarks.html", source = "BENCHMARKS.MD" },
  { title = "Examples", path = "examples.html", source = "EXAMPLES.MD" },
  { title = "Code of Conduct", path = "code-of-conduct.html", source = "CODE_OF_CONDUCT.MD" },
]